### ISSUE TITLE
Database models

### ISSUE THREAD

**Issue by nphilipp** [CentOS/duffy#47]
# Story

As a Duffy developer,
I want that various types of information are stored in a database,
because keeping them in a text file would be cumbersome.

# Acceptance Criteria

Database models exist for:

- [x] the nodes Duffy manages: #63
- [x] the projects able to request nodes
- [x] the users which contribute to projects
- [x] the sessions for which nodes are reserved

**Comment by gridhead** [comment]
Fixed in #74
