### ISSUE TITLE
Expose Database models in web API

### ISSUE THREAD

**Issue by nphilipp** [CentOS/duffy#77]
# Story

As a user of Duffy,
I want to be able to manage the various objects via the API,
because doing this with a DB CLI tool plain sucks.

# Acceptance Criteria

API endpoints exist to add/edit/delete…

- [x] Projects: #86
- [x] ~~Users: #80~~
- [x] ~~SSH Keys: #91~~
- [x] Nodes: #89 
- [x] Sessions: #87

# Background

Individual endpoints should provide a “RESTful” API, i.e. fulfil these acceptance criteria:

```
# Acceptance Criteria

Implement…
- [ ] a `GET` method to list items of the type
- [ ] a `POST` method to create new items of the type
- [ ] a `DELETE` method to delete items of a type (only where applicable?)
```

**Comment by nphilipp** [comment]
Closing this as all tracked issues are done.
